（6-2）従業員曖昧検索を実装しました.
pockytabetai/ex-emp-management-bugfix pull request #15
Opened 2022-11-21 06:57 UTC by pockytabetai

お疲れ様です。表題の通り、従業員曖昧検索機能を実装しました。
お手数ですがレビューをよろしくお願いいたします。

2022-11-21 07:18 UTC, pockytabetai commented
１度目のpushののちに、従業員の入社日順に出力できるようにSQL文を修正いたしました。
合わせてご確認いただけますと幸いです。

2022-11-21 08:01 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-21 08:01 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/repository/EmployeeRepository.java
> +	public List<Employee> findByPartOfName(String name) {
・JavaDocコメントも書きましょう。

2022-11-21 08:01 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/EmployeeService.java
> +
・JavaDocコメントも書きましょう。

2022-11-22 05:07 UTC, pockytabetai commented
お疲れ様です。
ご教示いただいた点について、改修いたしました。
お手隙の際にレビューいただければ幸いです。

2022-11-22 08:48 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-11-22 08:48 UTC, merged