(1-3)Eメール重複チェックを実装しました.
pockytabetai/ex-emp-management-bugfix pull request #8
Opened 2022-11-18 05:57 UTC by pockytabetai

お疲れ様です。
表題の通り、（1-3）課題の管理者登録画面にてEメールが既に登録されていた場合エラーメッセージの含まれた登録画面にリダイレクトする処理を実装しました。
ご多忙のところ恐縮ですが、ご確認いただけますと幸いです。

2022-11-18 08:46 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-18 08:46 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			model.addAttribute("error", "既に登録されたメールアドレスです");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-11-18 08:46 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +	public boolean isDuplicate(String mailAddress) {
JavaDocコメントを書きましょう。

2022-11-21 02:33 UTC, pockytabetai commented
お疲れ様です。
差し戻しのあった(1-3)(1-5)を同じブランチ上で改修してしまいました。
また、最新のcommitコメントのひとつ前のcommitについては無視していただければと思います。

お手数ですが、ご確認をお願いいたします。

2022-11-21 07:49 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-21 07:49 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			}
これを99行目のif文の下に移動してください。

2022-11-21 07:49 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
>  			return "administrator/insert";
上記の対応をした上でこのreturn文は不要です。(ない方がユーザの利便性が上がります。)
理由は考えていただきたいですが、わからない場合は質問するかできている人に確認をお願いします。

2022-11-21 07:51 UTC, igamasayuki commented
1-3と1-5を1-3ブランチで行なっているため1-5のプルリクは取り下げました。

そのため、こちらのプルリクのタイトルに1-5の番号も追加するように修正をお願いします。

2022-11-21 08:18 UTC, pockytabetai commented
お疲れ様です。
プルリク名を編集し、
ご指摘いただいた部分に関して修正いたしました。
>return文は不要です。(ない方がユーザの利便性が上がります。)
上記については、コードの順次進行を考慮したところ、同様の処理を実行しているため削除いたしました。
お手数ですがご確認をお願いいたします。

2022-11-21 08:26 UTC, pockytabetai commented
お疲れ様です。
プルリク名を編集し、
ご指摘いただいた部分に関して修正いたしました。
お手数ですが再度レビューをお願いいたします。

2022-11-22 08:47 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-11-22 08:47 UTC, merged